repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: .venv/Scripts/ruff.exe check --fix
        language: system
        stages: [pre-commit]
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff format
        entry: .venv/Scripts/ruff.exe format
        language: system
        stages: [pre-commit]
        types_or: [python, pyi]

      - id: pyright
        name: pyright
        entry: .venv/Scripts/pyright.exe
        language: system
        pass_filenames: false
        stages: [pre-push]

      - id: pytest
        name: pytest
        entry: .venv/Scripts/python.exe scripts/run-tests.py full
        language: system
        pass_filenames: false
        stages: [pre-push]
